# application.properties (common settings for all environments)
# This file contains default properties used across all environments
spring.application.name=stock-advisor
server.port=8080

# Logging configuration
logging.level.root=INFO
logging.level.org.springframework.web=INFO
logging.level.com.example=INFO

# overide Bean
spring.main.allow-bean-definition-overriding=true

# Default profile to use when none is specified
spring.profiles.active=dev